### ISSUE TITLE
App FC when accessing  saved file

### ISSUE THREAD

**Issue by jdstrydom** [tejado/Authorizer#7] opened 2017-08-09 08:39 UTC
This happens when opening previously created file rw or ro. It also FC when using the widget linked to file. If you need a logcat, I can provide. 

Android 7.1 Samsung Galaxy J5

**Comment by tejado** [comment] 2017-08-09 09:05
Thanks a lot for reporting this issue. A logcat would be really nice! If you don't want to provide it here, you can send it to tjado@maecke.de

**Comment by jdstrydom** [comment] 2017-08-09 13:00
08-09 11:45:10.823 I/ActivityManager(839): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=net.tjado.passwdsafe/.FileListActivity (has extras)} from uid 10022 on display 0
08-09 11:45:13.216 E/AndroidRuntime(19724): Process: net.tjado.passwdsafe, PID: 19724
08-09 11:45:13.216 E/AndroidRuntime(19724): 	at net.tjado.passwdsafe.PasswdSafeOpenFileFragment$1.onGlobalLayout(PasswdSafeOpenFileFragment.java:204)
08-09 11:45:13.228 W/ActivityManager(839):   Force finishing activity net.tjado.passwdsafe/.PasswdSafe
08-09 11:45:13.306 E/AppCrashReceiver(17974): net.tjado.passwdsafe stopped unexpectedly...
08-09 11:45:13.364 I/WindowManager(839): WIN DEATH: Window{66eea0b u0 net.tjado.passwdsafe/net.tjado.passwdsafe.PasswdSafe}
08-09 11:45:13.369 W/InputDispatcher(839): channel 'da56a6b net.tjado.passwdsafe/net.tjado.passwdsafe.FileListActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
08-09 11:45:13.369 E/InputDispatcher(839): channel 'da56a6b net.tjado.passwdsafe/net.tjado.passwdsafe.FileListActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
08-09 11:45:13.371 I/ActivityManager(839): Process net.tjado.passwdsafe (pid 19724) has died
08-09 11:45:13.374 I/WindowManager(839): WIN DEATH: Window{da56a6b u0 net.tjado.passwdsafe/net.tjado.passwdsafe.FileListActivity}
08-09 11:45:13.374 W/InputDispatcher(839): Attempted to unregister already unregistered input channel 'da56a6b net.tjado.passwdsafe/net.tjado.passwdsafe.FileListActivity (server)'
08-09 11:45:13.392 I/ActivityManager(839): Start proc 19898:net.tjado.passwdsafe/u0a130 for activity net.tjado.passwdsafe/.FileListActivity
08-09 11:45:14.602 I/ActivityManager(839): Displayed net.tjado.passwdsafe/.FileListActivity: +1s223ms
08-09 11:45:15.907 I/ActivityManager(839): START u0 {act=net.tjado.passwdsafe.action.VIEW dat=<web url omitted> cmp=net.tjado.passwdsafe/.PasswdSafe} from uid 10130 on display 0
08-09 11:45:16.413 I/ActivityManager(839): Displayed net.tjado.passwdsafe/.PasswdSafe: +487ms

**Comment by tejado** [comment] 2017-08-11 10:41
Okay, I also received your logcat per mail. Thanks! It seems that you are not the only one with this issue. 

Sadly, I can't reproduce it. Can you provide me the exact steps that will lead to the FC? And can you explain me, what you mean with "It also FC when using the widget linked to file" ? Thanks a lot!

**Comment by jdstrydom** [comment] 2017-08-18 22:29
Apologies for only replying now. It happens for me when creating a new file, insert a record and close app. When the app is opened and the password file selected and password entered, the record will be displayed. Clicking on anything, or navigating in the app anywhere will then cause a FC. When a widget is created linked to a password file, clicking the widget will cause app FC immediately. I hope I explained properly

**Comment by tejado** [comment] 2017-08-19 13:12
Sorry but I was not able to reproduce it :/ I hope I found & fixed the issue. The new version should be soon in the stores. Or you can download the apk over release [v0.2.5-beta](https://github.com/tejado/Authorizer/releases/tag/v0.2.5-beta).

Feedback would be really great!

**Comment by tejado** [comment] 2018-09-30 11:00
Should be fixed with the latest releases.

**Closed as completed by tejado** 2018-09-30 11:00 UTC
Labels: bug
