### ISSUE TITLE
Doesn't type G reliably

### ISSUE THREAD

**Issue by webtroter** [tejado/Authorizer#38] opened 2021-11-19 14:55 UTC
Hi,

It seems the app has a problem typing the `g` character reliably.

I added a record with username gg, and password gggg-gggg.

Authorizer types `g [tab] ggg-gggg`, instead of the correct `gg [tab] gggg-gggg`

I also tested with a different keybord layout (neo 2.0), and it typed the correct numbers of characters, just not a `g`, but a `i`.

And I just tested with capital G, and it just doesn't want to type it. Username GG, types nothing.

**Comment by tejado** [comment] 2021-11-19 15:53
Hi,

this sounds strange - never had any issues with the character "g". I just testet it and it worked fine for me.
On what operating system did this occur? Could you test it on a different computer and report back your findings, please?

**Comment by webtroter** [comment] 2021-11-19 16:58
Ok. I just tested on another computer and it is the same. Both are Windows 10.

My phone is OnePlus 6, running LineageOS 18.1

**Comment by Alexander-Shukaev** [comment] 2022-01-03 13:16
Hi, unfortunately, I have to second this.  In fact, this is not particularly related to <kbd>g</kbd>, it's a general issue.  For instance, I also noticed issues with handling of key codes dependent on the <kbd>Shift</kbd> modifier being pressed.  For example, in certain combinations of words, if <kbd>H</kbd> is expected as per password, Authroizer may output <kbd>h</kbd>, or if <kbd>:</kbd> is expected as per password, Authorizer may output <kbd>;</kbd>.  That is it swallows <kbd>Shift</kbd> sometimes.  Sometimes here and word "reliably" in the name of the topic might be confusing, as in fact, if the issue is there, then it is persistent with respect to a particular combination of words/letters in password, so it depends on a particular password whether the issue will be there or not and it stays like that.  It currently might be a major blocker to use certain arbitrary desired passwords, one has to be very careful to come up with something that does not expose this issue.

**Comment by tejado** [comment] 2022-01-03 15:52
Hi,
thanks for your feedback. At general this blocker should be solveable because Authorizer sends just key codes as your normal keyboard. As in my tests it worked perfectly fine, it may have something to do with your keyboard layout. What language your target system is on? Is the keyboard on the operating system configured in english or in a other language @webtroter and @Alexander-Shukaev ?
And which default language (settings -> Auto-Type Keyboard Layout) do you use in Authorizer? You can change that for a particular auto-typing if you press the button (e.g. Name, Password or Name/Pass) longer, then an popup opens where you can choose the output language.

For a further debugging step, it would be helpful if you can download the debug version (CAREFUL: this version logs passwords in cleartext, so use this only for debugging purposes -> so with test passwords), get the log of Authorizer over logcat, paste it into pastebin and show it here. Then I can check if there is some issue in the scan code output.

**Comment by webtroter** [comment] 2022-01-05 22:26
I use Windows in English US with the Canadian French keyboard layout (Alt
Gr + 2 = @), and us layout.

**Comment by tejado** [comment] 2022-09-18 18:16
Should be fixed by #43

**Closed as completed by tejado** 2022-09-18 18:16 UTC
